services:
  web:
    build: .
    ports:
      - "5000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:15.6
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_PASSWORD=nit6150"

  pgAdmin:
    image: dpage/pgadmin4:8.4
    ports:
      - "2345:80"
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=nit6150@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=nit6150'
    volumes:
      - pgAdmin_data:/var/lib/pgAdmin
    
volumes:
  postgres_data:
  pgAdmin_data:

